version: '3.4'

services:
  api:
    image: testforumapp
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Default=Server=db;Database=TestForum;User Id=sa;Password=zaq1@WSX;
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=zaq1@WSX
      - MSSQL_PID=Express
    ports:
      - "1433:1433"